### ISSUE TITLE
Migrate checkNewVersion and sendAnonymousUsage 

### ISSUE THREAD

**Issue by pierreduchemin** [containous/traefik-migration-tool#10]
Hi folks,

First of all, thank you for Traefik and this migration tool!

I have tried it and noticed that some parameters were not migrated.

https://github.com/containous/traefik-migration-tool/blob/18ef516dcc24129bcb3d02d33c26f4e8367e3651/static/configuration.go#L29

Why are those lines forced and not migrated like the others?

**Comment by ldez** [comment]
Hello,

fixed in e5d9a8d
